version: "3.8"

services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_DATABASE=mariadb
      - DB_PORT=3306
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: mariadb_container
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=test123
      - MYSQL_DATABASE=mariadb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
