name: CI/CD using GitHub Actions & Docker

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Debug: List workspace files"
        run: ls -al $GITHUB_WORKSPACE

      - name: Docker build & push to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -f $GITHUB_WORKSPACE/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/snake-game $GITHUB_WORKSPACE
          docker push ${{ secrets.DOCKER_USERNAME }}/snake-game

      - name: Upload project files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."
          target: "/home/ubuntu/snake-game-ci-cd"

      - name: Deploy with docker-compose (preserving DB data)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/snake-game-ci-cd
            # 컨테이너 중지 및 삭제 (볼륨은 유지 → 기존 DB 데이터 보존)
            docker-compose down || true
            docker-compose up -d --build
            docker image prune -a -f || true
